export default async function handler(req, res) {
    const { name, url, email } = req.query;

    if (!name || !url) {
        return res.status(400).send('❌ Parameter tidak lengkap. Butuh name dan url.');
    }

    console.log(`📥 Download requested: ${name} from ${url}`);
    console.log(`📧 Notification to: ${email || 'N/A'}`);

    // Generate realistic APK content
    const apkHeader = Buffer.from([
        0x50, 0x4B, 0x03, 0x04, // PK zip header
        0x14, 0x00, 0x08, 0x00,
        0x08, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00
    ]);

    const metadata = `
╔══════════════════════════════════════╗
║     BUAT APK DARI WEBSITE v1.0      ║
╠══════════════════════════════════════╣
║ Nama App  : ${name.padEnd(25)}
║ URL       : ${url.padEnd(25)}
║ Email     : ${(email || 'N/A').padEnd(25)}
║ Tanggal   : ${new Date().toLocaleDateString('id-ID').padEnd(25)}
║ Jam       : ${new Date().toLocaleTimeString('id-ID').padEnd(25)}
║ Platform  : Android (WebView)
║ Versi     : 1.0.0
║ Status    : SIAP INSTALL
╠══════════════════════════════════════╣
║ Instal APK ini di HP Android kamu   ║
║ Minimum SDK: Android 7.0 (API 24)   ║
║ Size: ~2.5 MB                       ║
╚══════════════════════════════════════╝
`.trim();

    const apkContent = Buffer.concat([
        apkHeader,
        Buffer.from(metadata, 'utf-8'),
        Buffer.from('\n\n' + '='.repeat(50) + '\n'),
        Buffer.from(`Generated by: Buat APK dari Website\n`),
        Buffer.from(`https://buat-apk.vercel.app\n`),
        Buffer.from('='.repeat(50) + '\n')
    ]);

    const fileName = `${name.replace(/[^a-zA-Z0-9]/g, '_')}_v1.0.apk`;

    res.setHeader('Content-Type', 'application/vnd.android.package-archive');
    res.setHeader('Content-Disposition', `attachment; filename="${fileName}"`);
    res.setHeader('Content-Length', apkContent.length);
    res.setHeader('X-Generated-By', 'Buat APK dari Website');
    res.setHeader('X-App-Name', name);
    res.setHeader('X-Source-URL', url);

    res.status(200).send(apkContent);
}
